In [2]:
import numpy as np

mat = np.array([
    [-1, 1, 0, 0, 0, 0],
    [0, 1, -1, 0, 0, 0],
    [0, 0, -1, 1, 0, 0],
    [-1, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, -1]
])

print(np.invert(mat))

[[ 0 -2 -1 -1 -1 -1]
 [-1 -2  0 -1 -1 -1]
 [-1 -1  0 -2 -1 -1]
 [ 0 -1 -1 -1 -1 -2]
 [-1 -1 -1 -1 -2 -1]
 [-2 -1 -1 -1 -1  0]]
